error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at Connection.openUri (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\BL_Backend\\fundo-project\\build\\config\\database.js:22:39)\n    at tryCatch (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:17)\n    at _next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:17:9)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:7\n    at new Promise (<anonymous>)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:14:12","timestamp":"2025-02-10T04:33:48.563Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\BL_Backend\\fundo-project\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:17)\n    at _next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:17:9)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:7\n    at new Promise (<anonymous>)\n    at apply (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:14:12)\n    at database (D:\\BL_Backend\\fundo-project\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\BL_Backend\\fundo-project\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1256:14)\n    at Module._compile (D:\\BL_Backend\\fundo-project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)\n    at Object.newLoader [as .js] (D:\\BL_Backend\\fundo-project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1119:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:960:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\node\\src\\_babel-node.ts:159:12)\n    at Module._compile (node:internal/modules/cjs/loader:1256:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)\n    at Module.load (node:internal/modules/cjs/loader:1119:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:960:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2025-02-10T04:37:05.689Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/67a983f57f68e4261039dcb0 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-10T04:44:24.251Z"}
error: 
    status - 500 
    message - ValidationError: "name" length must be at least 4 characters long 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T04:55:00.356Z"}
error: 
    status - 500 
    message - ValidationError: "name" must be a string 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T04:55:18.648Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token , in JSON at position 20
    at JSON.parse (<anonymous>)
    at parse (D:\BL_Backend\fundo-project\node_modules\body-parser\lib\types\json.js:92:19)
    at D:\BL_Backend\fundo-project\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:238:16)
    at done (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T05:38:20.376Z"}
error: 
    status - 500 
    message - ValidationError: "value" must be of type object 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T05:47:41.852Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.number(...).email is not a function
    at registerValidator (D:\BL_Backend\fundo-project\src\validators\/user.validator.js:18:8)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\BL_Backend\fundo-project\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BL_Backend\fundo-project\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at D:\BL_Backend\fundo-project\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:238:16)
    at done (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T09:10:26.314Z"}
error: 
    status - 500 
    message - ValidationError: Only Gmail accounts (@gmail.com) are allowed 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T09:11:29.611Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-11T04:38:16.640Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected string in JSON at position 29
    at JSON.parse (<anonymous>)
    at parse (D:\BL_Backend\fundo-project\node_modules\body-parser\lib\types\json.js:92:19)
    at D:\BL_Backend\fundo-project\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:238:16)
    at done (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-11T04:38:58.232Z"}
error: 
    status - 500 
    message - ValidationError: Password must be at least 8 characters 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-11T04:39:12.699Z"}
