error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at Connection.openUri (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\BL_Backend\\fundo-project\\build\\config\\database.js:22:39)\n    at tryCatch (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:17)\n    at _next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:17:9)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:7\n    at new Promise (<anonymous>)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:14:12","timestamp":"2025-02-10T04:33:48.563Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\BL_Backend\\fundo-project\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:17)\n    at _next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:17:9)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:7\n    at new Promise (<anonymous>)\n    at apply (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:14:12)\n    at database (D:\\BL_Backend\\fundo-project\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\BL_Backend\\fundo-project\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1256:14)\n    at Module._compile (D:\\BL_Backend\\fundo-project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)\n    at Object.newLoader [as .js] (D:\\BL_Backend\\fundo-project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1119:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:960:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\node\\src\\_babel-node.ts:159:12)\n    at Module._compile (node:internal/modules/cjs/loader:1256:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)\n    at Module.load (node:internal/modules/cjs/loader:1119:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:960:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2025-02-10T04:37:05.689Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/67a983f57f68e4261039dcb0 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-10T04:44:24.251Z"}
error: 
    status - 500 
    message - ValidationError: "name" length must be at least 4 characters long 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T04:55:00.356Z"}
error: 
    status - 500 
    message - ValidationError: "name" must be a string 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T04:55:18.648Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token , in JSON at position 20
    at JSON.parse (<anonymous>)
    at parse (D:\BL_Backend\fundo-project\node_modules\body-parser\lib\types\json.js:92:19)
    at D:\BL_Backend\fundo-project\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:238:16)
    at done (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T05:38:20.376Z"}
error: 
    status - 500 
    message - ValidationError: "value" must be of type object 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T05:47:41.852Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.number(...).email is not a function
    at registerValidator (D:\BL_Backend\fundo-project\src\validators\/user.validator.js:18:8)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\BL_Backend\fundo-project\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BL_Backend\fundo-project\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at D:\BL_Backend\fundo-project\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:238:16)
    at done (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T09:10:26.314Z"}
error: 
    status - 500 
    message - ValidationError: Only Gmail accounts (@gmail.com) are allowed 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-10T09:11:29.611Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-11T04:38:16.640Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected string in JSON at position 29
    at JSON.parse (<anonymous>)
    at parse (D:\BL_Backend\fundo-project\node_modules\body-parser\lib\types\json.js:92:19)
    at D:\BL_Backend\fundo-project\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:238:16)
    at done (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-11T04:38:58.232Z"}
error: 
    status - 500 
    message - ValidationError: Password must be at least 8 characters 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2025-02-11T04:39:12.699Z"}
error: uncaughtException: password is not defined
ReferenceError: password is not defined
    at _callee2$ (D:\BL_Backend\fundo-project\src\services\/user.service.js:27:43)
    at tryCatch (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Tue Feb 11 2025 14:15:00 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":3211.875},"process":{"argv":["node","D:\\BL_Backend\\fundo-project\\src\\index.js"],"cwd":"D:\\BL_Backend\\fundo-project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18306714,"external":19855617,"heapTotal":52699136,"heapUsed":48914208,"rss":93401088},"pid":7736,"uid":null,"version":"v18.17.0"},"stack":"ReferenceError: password is not defined\n    at _callee2$ (D:\\BL_Backend\\fundo-project\\src\\services\\/user.service.js:27:43)\n    at tryCatch (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:17)\n    at _next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:17:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-02-11T08:45:00.225Z","trace":[{"column":43,"file":"D:\\BL_Backend\\fundo-project\\src\\services\\/user.service.js","function":"_callee2$","line":27,"method":null,"native":false},{"column":16,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":74,"method":"next","native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":17,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: uncaughtException: Illegal arguments: undefined, undefined
Error: Illegal arguments: undefined, undefined
    at _async (D:\BL_Backend\fundo-project\node_modules\bcryptjs\dist\bcrypt.js:286:46)
    at D:\BL_Backend\fundo-project\node_modules\bcryptjs\dist\bcrypt.js:307:17
    at new Promise (<anonymous>)
    at Object.compare (D:\BL_Backend\fundo-project\node_modules\bcryptjs\dist\bcrypt.js:306:20)
    at _callee2$ (D:\BL_Backend\fundo-project\src\services\/user.service.js:27:35)
    at tryCatch (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Tue Feb 11 2025 14:15:37 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":3249.5},"process":{"argv":["node","D:\\BL_Backend\\fundo-project\\src\\index.js"],"cwd":"D:\\BL_Backend\\fundo-project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19676803,"external":21227927,"heapTotal":95666176,"heapUsed":61544224,"rss":135516160},"pid":8360,"uid":null,"version":"v18.17.0"},"stack":"Error: Illegal arguments: undefined, undefined\n    at _async (D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js:286:46)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js:307:17\n    at new Promise (<anonymous>)\n    at Object.compare (D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js:306:20)\n    at _callee2$ (D:\\BL_Backend\\fundo-project\\src\\services\\/user.service.js:27:35)\n    at tryCatch (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:17)\n    at _next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:17:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-02-11T08:45:37.847Z","trace":[{"column":46,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js","function":"_async","line":286,"method":null,"native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js","function":null,"line":307,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":20,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js","function":"Object.compare","line":306,"method":"compare","native":false},{"column":35,"file":"D:\\BL_Backend\\fundo-project\\src\\services\\/user.service.js","function":"_callee2$","line":27,"method":null,"native":false},{"column":16,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":74,"method":"next","native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":17,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: uncaughtException: Illegal arguments: undefined, undefined
Error: Illegal arguments: undefined, undefined
    at _async (D:\BL_Backend\fundo-project\node_modules\bcryptjs\dist\bcrypt.js:286:46)
    at D:\BL_Backend\fundo-project\node_modules\bcryptjs\dist\bcrypt.js:307:17
    at new Promise (<anonymous>)
    at Object.compare (D:\BL_Backend\fundo-project\node_modules\bcryptjs\dist\bcrypt.js:306:20)
    at _callee2$ (D:\BL_Backend\fundo-project\src\services\/user.service.js:27:35)
    at tryCatch (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Tue Feb 11 2025 14:18:45 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":3437.203},"process":{"argv":["node","D:\\BL_Backend\\fundo-project\\src\\index.js"],"cwd":"D:\\BL_Backend\\fundo-project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18363709,"external":19912612,"heapTotal":53485568,"heapUsed":49794832,"rss":94744576},"pid":4496,"uid":null,"version":"v18.17.0"},"stack":"Error: Illegal arguments: undefined, undefined\n    at _async (D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js:286:46)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js:307:17\n    at new Promise (<anonymous>)\n    at Object.compare (D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js:306:20)\n    at _callee2$ (D:\\BL_Backend\\fundo-project\\src\\services\\/user.service.js:27:35)\n    at tryCatch (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:17)\n    at _next (D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:17:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-02-11T08:48:45.546Z","trace":[{"column":46,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js","function":"_async","line":286,"method":null,"native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js","function":null,"line":307,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":20,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\bcryptjs\\dist\\bcrypt.js","function":"Object.compare","line":306,"method":"compare","native":false},{"column":35,"file":"D:\\BL_Backend\\fundo-project\\src\\services\\/user.service.js","function":"_callee2$","line":27,"method":null,"native":false},{"column":16,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":74,"method":"next","native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":17,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-11T09:22:29.299Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-11T09:22:56.672Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-11T09:22:57.980Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-11T09:24:29.186Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes 
      method - POST 
      IP - ::1
     {"timestamp":"2025-02-11T09:49:45.049Z"}
error: uncaughtException: Note validation failed: userId: Path `userId` is required.
ValidationError: Note validation failed: userId: Path `userId` is required.
    at model.Document.invalidate (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\document.js:2788:32)
    at D:\BL_Backend\fundo-project\node_modules\mongoose\lib\document.js:2580:17
    at D:\BL_Backend\fundo-project\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {"date":"Tue Feb 11 2025 15:21:28 GMT+0530 (India Standard Time)","error":{"_message":"Note validation failed","errors":{"userId":{"kind":"required","message":"Path `userId` is required.","name":"ValidatorError","path":"userId","properties":{"message":"Path `userId` is required.","path":"userId","type":"required"}}},"message":"Note validation failed: userId: Path `userId` is required.","name":"ValidationError"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":7200.593},"process":{"argv":["node","D:\\BL_Backend\\fundo-project\\src\\index.js"],"cwd":"D:\\BL_Backend\\fundo-project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18465734,"external":20014637,"heapTotal":57942016,"heapUsed":53451128,"rss":100220928},"pid":22520,"uid":null,"version":"v18.17.0"},"stack":"ValidationError: Note validation failed: userId: Path `userId` is required.\n    at model.Document.invalidate (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js:2788:32)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js:2580:17\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\schematype.js:1273:9\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2025-02-11T09:51:28.945Z","trace":[{"column":32,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js","function":"model.Document.invalidate","line":2788,"method":"invalidate","native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js","function":null,"line":2580,"method":null,"native":false},{"column":9,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\schematype.js","function":null,"line":1273,"method":null,"native":false},{"column":11,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":77,"method":null,"native":false}]}
error: uncaughtException: Note validation failed: userId: Path `userId` is required.
ValidationError: Note validation failed: userId: Path `userId` is required.
    at model.Document.invalidate (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\document.js:2788:32)
    at D:\BL_Backend\fundo-project\node_modules\mongoose\lib\document.js:2580:17
    at D:\BL_Backend\fundo-project\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {"date":"Tue Feb 11 2025 15:22:12 GMT+0530 (India Standard Time)","error":{"_message":"Note validation failed","errors":{"userId":{"kind":"required","message":"Path `userId` is required.","name":"ValidatorError","path":"userId","properties":{"message":"Path `userId` is required.","path":"userId","type":"required"}}},"message":"Note validation failed: userId: Path `userId` is required.","name":"ValidationError"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":7243.812},"process":{"argv":["node","D:\\BL_Backend\\fundo-project\\src\\index.js"],"cwd":"D:\\BL_Backend\\fundo-project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18555984,"external":20107108,"heapTotal":97263616,"heapUsed":54918176,"rss":136732672},"pid":3296,"uid":null,"version":"v18.17.0"},"stack":"ValidationError: Note validation failed: userId: Path `userId` is required.\n    at model.Document.invalidate (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js:2788:32)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js:2580:17\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\schematype.js:1273:9\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2025-02-11T09:52:12.157Z","trace":[{"column":32,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js","function":"model.Document.invalidate","line":2788,"method":"invalidate","native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js","function":null,"line":2580,"method":null,"native":false},{"column":9,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\schematype.js","function":null,"line":1273,"method":null,"native":false},{"column":11,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":77,"method":null,"native":false}]}
error: uncaughtException: Note validation failed: userId: Path `userId` is required.
ValidationError: Note validation failed: userId: Path `userId` is required.
    at model.Document.invalidate (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\document.js:2788:32)
    at D:\BL_Backend\fundo-project\node_modules\mongoose\lib\document.js:2580:17
    at D:\BL_Backend\fundo-project\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {"date":"Tue Feb 11 2025 15:22:34 GMT+0530 (India Standard Time)","error":{"_message":"Note validation failed","errors":{"userId":{"kind":"required","message":"Path `userId` is required.","name":"ValidatorError","path":"userId","properties":{"message":"Path `userId` is required.","path":"userId","type":"required"}}},"message":"Note validation failed: userId: Path `userId` is required.","name":"ValidationError"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":7266.25},"process":{"argv":["node","D:\\BL_Backend\\fundo-project\\src\\index.js"],"cwd":"D:\\BL_Backend\\fundo-project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19866307,"external":21417431,"heapTotal":97202176,"heapUsed":62107176,"rss":139591680},"pid":19856,"uid":null,"version":"v18.17.0"},"stack":"ValidationError: Note validation failed: userId: Path `userId` is required.\n    at model.Document.invalidate (D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js:2788:32)\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js:2580:17\n    at D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\schematype.js:1273:9\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2025-02-11T09:52:34.594Z","trace":[{"column":32,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js","function":"model.Document.invalidate","line":2788,"method":"invalidate","native":false},{"column":17,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\document.js","function":null,"line":2580,"method":null,"native":false},{"column":9,"file":"D:\\BL_Backend\\fundo-project\\node_modules\\mongoose\\lib\\schematype.js","function":null,"line":1273,"method":null,"native":false},{"column":11,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":77,"method":null,"native":false}]}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '._id' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/._id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T02:56:21.655Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '_id' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/_id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T02:56:39.465Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: 'id' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T02:56:48.702Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: ':_id' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/:_id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T02:57:33.503Z"}
error: 
    status - 500 
    message - ReferenceError: _userId is not defined
    at _callee2$ (D:\BL_Backend\fundo-project\src\services\/Note.service.js:18:48)
    at tryCatch (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at Object.apply (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at Object.updateNote (D:\BL_Backend\fundo-project\src\services\/Note.service.js:17:24)
    at _callee2$ (D:\BL_Backend\fundo-project\src\controllers\/note.controller.js:18:36)
    at tryCatch (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at updateNote (D:\BL_Backend\fundo-project\src\controllers\/note.controller.js:16:24)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\BL_Backend\fundo-project\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:284:15
    at param (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:365:14)
    at param (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:421:3)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BL_Backend\fundo-project\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BL_Backend\fundo-project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:328:13)
    at D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BL_Backend\fundo-project\node_modules\express\lib\router\index.js:280:10)
    at D:\BL_Backend\fundo-project\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:238:16)
    at done (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\BL_Backend\fundo-project\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12) 
    url - /api/v1/notes/:_userId 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T02:58:57.061Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value ":_id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/:_id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:04:40.469Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value ":_id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/:_id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:06:01.762Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "_id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/_id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:06:42.200Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:14:09.184Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:14:43.047Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "_id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/_id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:14:56.448Z"}
error: 
    status - 500 
    message - ReferenceError: isTrash is not defined
    at _callee2$ (D:\BL_Backend\fundo-project\src\services\/Note.service.js:18:15)
    at tryCatch (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:15:18.634Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at _callee2$ (D:\BL_Backend\fundo-project\src\controllers\/note.controller.js:19:16)
    at tryCatch (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (D:\BL_Backend\fundo-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:18:27.875Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "_id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/_id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:21:32.283Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:21:37.978Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:21:58.633Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "_id" (type string) at path "_id" for model "Note"
    at model.Query.exec (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\BL_Backend\fundo-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/_id 
    method - PUT 
    IP - ::1
   {"timestamp":"2025-02-12T03:24:20.518Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-12T03:29:34.596Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-12T03:30:44.021Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-12T03:35:02.500Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-12T03:37:49.955Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-12T03:39:16.036Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-12T03:45:59.356Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users 
      method - GET 
      IP - ::1
     {"timestamp":"2025-02-12T03:48:35.723Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/notes/67ab1e0bc9177107a4fc9452 
      method - PUT 
      IP - ::1
     {"timestamp":"2025-02-12T04:26:18.049Z"}
